package media

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"time"

	gifdomain "github.com/brandopakel/gogifgenerator/internal/gif"
	"github.com/brandopakel/gogifgenerator/internal/store"
)

const maxGeneratedAssetBytes = 64 << 20

type GeneratedAsset struct {
	Prompt string
	Engine string
	Spec   gifdomain.Spec
	Data   []byte
	Source *GeneratedSource
}

// GeneratedSource preserves the attribution and license obligations of a
// temporary provider reference without retaining the provider's media bytes.
type GeneratedSource struct {
	Provider      string
	ExternalID    string
	SourceURL     string
	Author        string
	LicenseID     string
	LicenseURL    string
	Attribution   string
	CommercialUse Permission
	Derivatives   Permission
	ShareAlike    bool
}

type GeneratedSaver interface {
	SaveGenerated(context.Context, GeneratedAsset) (Asset, error)
}

type GeneratedReader interface {
	OpenGenerated(context.Context, string) (Asset, io.ReadCloser, error)
}

// Library coordinates immutable blobs with their searchable catalog records.
type Library struct {
	repository *Repository
	blobs      store.BlobStore
	now        func() time.Time
	newID      func() (string, error)
}

func NewLibrary(repository *Repository, blobs store.BlobStore) *Library {
	return &Library{
		repository: repository,
		blobs:      blobs,
		now:        time.Now,
		newID:      newAssetID,
	}
}

func (l *Library) SaveGenerated(ctx context.Context, generated GeneratedAsset) (Asset, error) {
	if len(generated.Data) == 0 {
		return Asset{}, errors.New("generated asset is empty")
	}
	spec, err := generated.Spec.Normalize()
	if err != nil {
		return Asset{}, fmt.Errorf("normalize generated asset spec: %w", err)
	}
	id, err := l.newID()
	if err != nil {
		return Asset{}, fmt.Errorf("create asset ID: %w", err)
	}
	blob, err := l.blobs.Put(ctx, bytes.NewReader(generated.Data), store.PutBlobOptions{MaxBytes: maxGeneratedAssetBytes})
	if err != nil {
		return Asset{}, fmt.Errorf("store generated bytes: %w", err)
	}
	now := l.now().UTC()
	provenance := Provenance{
		Provider:   "gogif",
		ExternalID: id,
		Generator:  generated.Engine,
		ImportedAt: &now,
		VerifiedAt: &now,
	}
	rights := Rights{
		Status:        "generated-unreviewed",
		CommercialUse: PermissionUnknown,
		Derivatives:   PermissionUnknown,
	}
	if generated.Source != nil {
		provenance.SourceProvider = generated.Source.Provider
		provenance.SourceExternalID = generated.Source.ExternalID
		provenance.SourceURL = generated.Source.SourceURL
		provenance.Author = generated.Source.Author
		rights = Rights{
			Status:        "generated-from-licensed-reference",
			LicenseID:     generated.Source.LicenseID,
			LicenseURL:    generated.Source.LicenseURL,
			Attribution:   generated.Source.Attribution,
			CommercialUse: generated.Source.CommercialUse,
			Derivatives:   generated.Source.Derivatives,
			ShareAlike:    generated.Source.ShareAlike,
		}
	}
	asset := Asset{
		ID:         id,
		Kind:       KindGIF,
		State:      StateReady,
		Title:      spec.Caption,
		Prompt:     generated.Prompt,
		CreatedAt:  now,
		UpdatedAt:  now,
		Provenance: provenance,
		Rights:     rights,
		Moderation: Moderation{Status: "unreviewed"},
		Fingerprint: &Fingerprint{
			SHA256: blob.Digest,
		},
		Renditions: []Rendition{{
			Name:        "original",
			Format:      "gif",
			ContentType: "image/gif",
			Storage:     StorageManaged,
			BlobKey:     blob.Key,
			Width:       spec.Width,
			Height:      spec.Height,
			DurationMS:  int64(spec.Frames * spec.DelayMS),
			SizeBytes:   blob.Size,
		}},
	}
	if err := l.repository.Put(ctx, asset); err != nil {
		return Asset{}, fmt.Errorf("catalog generated asset: %w", err)
	}
	return asset, nil
}

// OpenGenerated only serves GoGIF-created managed bytes. Provider search
// results are external references and cannot cross this boundary.
func (l *Library) OpenGenerated(ctx context.Context, id string) (Asset, io.ReadCloser, error) {
	asset, err := l.repository.Get(ctx, id)
	if err != nil {
		return Asset{}, nil, err
	}
	if asset.State != StateReady || asset.Kind != KindGIF || asset.Provenance.Provider != "gogif" {
		return Asset{}, nil, store.ErrNotFound
	}
	for _, rendition := range asset.Renditions {
		if rendition.Name != "original" || rendition.Storage != StorageManaged || rendition.ContentType != "image/gif" {
			continue
		}
		reader, blob, err := l.blobs.Open(ctx, rendition.BlobKey)
		if err != nil {
			return Asset{}, nil, err
		}
		if blob.Size != rendition.SizeBytes {
			_ = reader.Close()
			return Asset{}, nil, errors.New("generated blob size does not match its catalog record")
		}
		return asset, reader, nil
	}
	return Asset{}, nil, store.ErrNotFound
}

func newAssetID() (string, error) {
	random := make([]byte, 12)
	if _, err := rand.Read(random); err != nil {
		return "", err
	}
	return "gif_" + hex.EncodeToString(random), nil
}
