package media

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	gifdomain "github.com/brandopakel/gogifgenerator/internal/gif"
	"github.com/brandopakel/gogifgenerator/internal/store"
)

const maxGeneratedAssetBytes = 64 << 20

type GeneratedAsset struct {
	Prompt string
	Engine string
	Spec   gifdomain.Spec
	Data   []byte
}

type GeneratedSaver interface {
	SaveGenerated(context.Context, GeneratedAsset) (Asset, error)
}

// Library coordinates immutable blobs with their searchable catalog records.
type Library struct {
	repository *Repository
	blobs      store.BlobStore
	now        func() time.Time
	newID      func() (string, error)
}

func NewLibrary(repository *Repository, blobs store.BlobStore) *Library {
	return &Library{
		repository: repository,
		blobs:      blobs,
		now:        time.Now,
		newID:      newAssetID,
	}
}

func (l *Library) SaveGenerated(ctx context.Context, generated GeneratedAsset) (Asset, error) {
	if len(generated.Data) == 0 {
		return Asset{}, errors.New("generated asset is empty")
	}
	spec, err := generated.Spec.Normalize()
	if err != nil {
		return Asset{}, fmt.Errorf("normalize generated asset spec: %w", err)
	}
	id, err := l.newID()
	if err != nil {
		return Asset{}, fmt.Errorf("create asset ID: %w", err)
	}
	blob, err := l.blobs.Put(ctx, bytes.NewReader(generated.Data), store.PutBlobOptions{MaxBytes: maxGeneratedAssetBytes})
	if err != nil {
		return Asset{}, fmt.Errorf("store generated bytes: %w", err)
	}
	now := l.now().UTC()
	asset := Asset{
		ID:        id,
		Kind:      KindGIF,
		State:     StateReady,
		Title:     spec.Caption,
		Prompt:    generated.Prompt,
		CreatedAt: now,
		UpdatedAt: now,
		Provenance: Provenance{
			Provider:   "gogif",
			ExternalID: id,
			Generator:  generated.Engine,
			ImportedAt: &now,
			VerifiedAt: &now,
		},
		Rights: Rights{
			Status:        "generated-unreviewed",
			CommercialUse: PermissionUnknown,
			Derivatives:   PermissionUnknown,
		},
		Moderation: Moderation{Status: "unreviewed"},
		Fingerprint: &Fingerprint{
			SHA256: blob.Digest,
		},
		Renditions: []Rendition{{
			Name:        "original",
			Format:      "gif",
			ContentType: "image/gif",
			Storage:     StorageManaged,
			BlobKey:     blob.Key,
			Width:       spec.Width,
			Height:      spec.Height,
			DurationMS:  int64(spec.Frames * spec.DelayMS),
			SizeBytes:   blob.Size,
		}},
	}
	if err := l.repository.Put(ctx, asset); err != nil {
		return Asset{}, fmt.Errorf("catalog generated asset: %w", err)
	}
	return asset, nil
}

func newAssetID() (string, error) {
	random := make([]byte, 12)
	if _, err := rand.Read(random); err != nil {
		return "", err
	}
	return "gif_" + hex.EncodeToString(random), nil
}
